#tweeter API credentials
tweeter:
  api:
    api-key: ${TWITTER_API_KEY}
    api-secret-key: ${TWITTER_API_SECRET_KEY}
    bearer-string: Bearer ${TWITTER_BEARER_TOKEN}
    bearer-token: ${TWITTER_BEARER_TOKEN}


#server-config
server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 600


#database and jpa/hibernate-config
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp


client:
  base-url: https://api.twitter.com